# Generated by Django 4.1.12 on 2023-11-04 08:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=255)),
                ('receiver_id', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_dateTime', models.DateTimeField(null=True)),
                ('created_dateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
